version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product_catalog_db
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product_network

volumes:
  postgres_data:

networks:
  product_network:
    driver: bridge
